name: CI - Testes Postman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Newman
        run: npm install -g newman

      - name: Instalar o reporter HTML
        run: npm install -g newman-reporter-html

      - name: Rodar testes com Newman e gerar report HTML 
        run: |
          newman run tests/disney-api-collection.json --reporters cli,html --reporter-html-export relatorio.html
          continue-on-error: true

      - name: Resultado da execução
        if: failure()
        run: echo "❌ Alguns testes falharam. Corrija antes de fazer merge."
      
      - name: Salvar o relatório como artefato
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-newman
          path: relatorio.html
